### ISSUE TITLE
Sample File & Get Info

### ISSUE THREAD

**Issue by daksamedia** [marpies/AIRTwitter-ANE#1]
Hi @marpies,
I'm very happy seeing this ANE, it's really good to try on my apps. Well, if you dont mind, would u provide sample code? 

According, the sample you gave, seems like u dont give us example how to get user info.

Thank u for the attention.

Regards

**Comment by marpies** [comment]
Right, currently there is no method to retrieve info about an arbitrary user, except the one currently logged in your app.

```
const user:AIRTwitterUser = AIRTwitter.getLoggedInUser( onLoggedInUserRetrieved );
if( user ) {
     // cached value returned
}
// if cached value is not returned callback will be triggered
function onLoggedInUserRetrieved(user:AIRTwitterUser, errorMessage:String):void {
     trace( user.name );
}
```

As soon as I have some time, I will add some methods to retrieve info for any user.

Thanks for opening the issue

**Comment by marpies** [comment]
Added methods to retrieve users info for their ID or screen name.

**Comment by daksamedia** [comment]
Alright @marpies
Thank you for a very fast response.
It's really worth to try.
Cheers!
