### ISSUE TITLE
Can I authorize the account in my app without Safari ??

### ISSUE THREAD

**Issue by badboybb** [marpies/AIRTwitter-ANE#10]
I get on the authorization in the Safari, Can I make the progress of authorization in a separate page?
I want to complete the all progress in my app, Does the ane have the function？？？

**Comment by marpies** [comment]
You can login with Twitter account that is set in the device's settings.

```as3
AIRTwitter.loginWithAccount( onTwitterLogin );

private function onTwitterLogin( errorMessage:String, wasCancelled:Boolean ):void {
    if( errorMessage ) {
        trace( "Login error: " + errorMessage );
    } else if( wasCancelled ) {
        trace( "Login cancelled" );
    } else {
        trace( "Successfully logged in" );
    }
}
```

Other than that, there is currently no other way to authorize users with this ANE.
