### ISSUE TITLE
Keep getting "User credentials are missing"

### ISSUE THREAD

**Issue by lucien144** [marpies/AIRTwitter-ANE#11]
Hi,
first of all, thanks for this and your hard work! 👏🏻

I'm working on ios/android app built using starling & feathers. I keep getting "User credentials are missing" after the browser redirects me back to the app after the successful authorization in a browser.

Even though I call the `AIRTwitter.init` as soon as I can, I keep getting this error. I followed the documentation, check all issues but still does not understand why this is happening. Seems to me like the credentials information are not passed from browser (~ url scheme) to the app correctly.

Any thoughts?

Thanks.

**Comment by marpies** [comment]
Hi @lucien144,

The *User credentials are missing* message should only appear once after calling `AIRTwitter.init` (in case user has not logged in previously) and not after a login attempt.

What's the response in your login callback and what device / system are you seeing this behavior on?

**Comment by lucien144** [comment]
Hi @marpies,
sorry for late reply. After some struggle, I've decided to implement my own twitter authorization which went well. You can close this now as the problem could on my side only.

Thanks.
