### ISSUE TITLE
Why I can't log the "login success" because "login cancelled",Please help me.

### ISSUE THREAD

**Issue by badboybb** [marpies/AIRTwitter-ANE#12]
Thank you for your code .I have be successful to use the ane to login with twitter.But now it doesn't work.
when I click the button of "login", I can come back to my app successfully .But the ane will tell me
 "Returned to app manually after login attempt, thus login cancelled". at first. Then tell me "[Airtwitter]login successful".
So Can you tell me the reason??
Can I give my suggestion to you ? Can you make the Event funcion of "onStatus" to be public.and When it determines." login success". Can you dispatch a event of the success.Then I can use the function of  "addEventListener" to distinguish. Please Help me ??

![qq 20170408180711](https://cloud.githubusercontent.com/assets/24217136/24827959/39419bae-1c86-11e7-846e-b6716c6bfbaa.png)

**Comment by marpies** [comment]
What device / system do you see this on?

It should work without having access to the `onStatus` method, but you can always make a fork of the repo and make any changes you need.
