### ISSUE TITLE
I login with twitter account successfully,but I got a wrong twitter ID

### ISSUE THREAD

**Issue by badboybb** [marpies/AIRTwitter-ANE#13]
Hello,I find a error of the ane .My twitter ID have 18 digits like "111111111111111111". And I use my twitter account to login to my app. and I login successfully. But When I want to get the twitter ID. 
The result is "111111111111111100". the last two digits of the twitter ID will be "00". and the last third digit will rounding. but if the digit of twitter ID less than 16, the twitter ID I got will be correct

example:
```
Real Twitter ID : 111111111111111111         Obtained  Twitter ID: 111111111111111100
Real Twitter ID : 111111111111111155         Obtained  Twitter ID: 111111111111111200
```

Can you fix the error?  Wish your answer

**Comment by marpies** [comment]
How do you get the twitter ID? It's possible that the ID is too large to fit in a numeric data type. Perhaps parsing it as `String` may help.

**Comment by badboybb** [comment]
Please check my Code with the screenshot. when I get the message of "login success". I use the function of 
"getLoggedInUser()"  to get the user message. and the tyep of twitter ID I got is number . so I change it to String. but it doesn't work .because I got the twitter ID from the ane .the ID is  like "111111111111111200"
the last two digit is 0.

Wish your answer!!!!
![Uploading QQ图片20170427111515.png…]()

**Comment by badboybb** [comment]
![dd](https://cloud.githubusercontent.com/assets/24217136/25466554/ff8606f6-2b3b-11e7-92dd-ebc4bd9bbc72.jpg)

**Comment by badboybb** [comment]
if I print the value of  (user.id). it will be the situation I said .So I suspect the ane is wrong
please help me !!!

**Comment by badboybb** [comment]
I find the ID got from AIRTwitterUser. the type of ID  in Number. the screenshot is the AIRTwitterUser 's code . And I make a test .
   if I definition a constant which type is Number. and make it be 111111111111111111 . then I print it .
the result is [test : 111111111111111100]. Hope your wish!!!!!!

The test code:
  var test:Number = 111111111111111111;
  trace("test : " + test );

**Comment by badboybb** [comment]
![ww](https://cloud.githubusercontent.com/assets/24217136/25467386/6b7354d2-2b40-11e7-8011-927ac00c9063.png)

**Comment by marpies** [comment]
Yes, I see. I will update the API. Please be patient.

**Comment by badboybb** [comment]
Thank you very much!!  Wish your updte!!!!!!!!!!

**Comment by marpies** [comment]
I updated the [ANE to v1.2.0](https://github.com/marpies/AIRTwitter-ANE/releases).

**Comment by badboybb** [comment]
thank you very much !! the problem has solved!!!!!!
