### ISSUE TITLE
Is it possible to login with tokens from dev.twitter.com

### ISSUE THREAD

**Issue by goodintention** [marpies/AIRTwitter-ANE#14]
Thank you for the effort and time you put in AIRTwitter-ANE 
Is it possible to login with tokens from dev.twitter.com ?
https://dev.twitter.com/oauth/overview/application-owner-access-tokens
I want to updatestatus of an existing twitter account not a user account
I see that accessToken and accessTokenSecret are read only properties
sorry if my question looks confusing I'm new to Oauth and twitter API

**Comment by marpies** [comment]
Hi,

Unfortunately, this feature is not currently supported. I will try to find the time to implement this.

**Comment by goodintention** [comment]
I appreciate that, thanks again for your work.

**Comment by marpies** [comment]
I added new method called [loginWithAccessToken](https://github.com/marpies/AIRTwitter-ANE/blob/master/actionscript/src/com/marpies/ane/twitter/AIRTwitter.as#L181-L198).

**Comment by goodintention** [comment]
Great!
