### ISSUE TITLE
error with updateStatus

### ISSUE THREAD

**Issue by xietianze** [marpies/AIRTwitter-ANE#15]
way 1:
//bmd
var bitmap:BitmapData = new myBitmapData();//some bmd in library
//encode
var bytes:ByteArray = bitmap.encode(bitmap.rect, new PNGEncoderOptions());
var file:File = File.applicationStorageDirectory.resolvePath("tempTwitter.png");
var st:FileStream = new FileStream();  st.open(file, FileMode.WRITE);  st.writeBytes(bytes);  st.close();
//share
AIRTwitter.updateStatus("share text", onTwiiterShared, null, [file.nativePath]);

this will not work because the callback onTwiiterShared returns a errorMessage : Error creating data for upload.

way 2:
//bmd
var bitmap:BitmapData = new myBitmapData();//some bmd in library
//share
AIRTwitter.updateStatus("share text", onTwiiterShared, null, [bitmap]);

this will lead the app to crash.

so as a whole i can't do that in neither way.
according to the doc: 	media:Array (default = null) — List of media files (String - URLs to local and remote images, BitmapData) - max. 4.

i can't get the correct way to use this Parameter: media, please help, thanks.

**Comment by marpies** [comment]
Thanks for reporting. Maybe something has changed with the Twitter's API, I'll check it out and let you know.

**Comment by xietianze** [comment]
there is another glitch:

AIRTwitter.updateStatus("share text", onTwiiterShared, null, null);

this on Android will not work, no update on the timeline, and no callback.

please take a look. thanks !

**Comment by marpies** [comment]
Sorry for the late reply. I just had a look at the media upload, but it still seems to be working correctly with the following code:

```as3
private var mMedia:Bitmap = new Bitmap(...);

AIRTwitter.updateStatus( "message", onStatusUpdated, null, [mMedia.bitmapData, "https://gamua.com/img/home/starling-look-scared.png"]);
```

This creates a tweet with both the `BitmapData` and remote image.

To upload `BitmapData` saved to a file, try using the `cacheDirectory`. That has worked for me:

```as3
var file:File = File.cacheDirectory.resolvePath("tempTwitter.png");
...
AIRTwitter.updateStatus( "message", onStatusUpdated, null, [file.nativePath]);
```

As for the callback not getting triggered, I fixed an issue where the callback failed to be called if there was an error. Please try using the [latest release](https://github.com/marpies/AIRTwitter-ANE/releases) and also enable the extension logs to see whether you have any errors when attempting to create a tweet.

**Comment by xietianze** [comment]
All are fixed now, thanks a lot marpies.
this can be closed now,  much appreciated !!!
