### ISSUE TITLE
Export Build Error

### ISSUE THREAD

**Issue by polyGeek** [marpies/AIRTwitter-ANE#16]
I'm trying to integrate your ANE – great ANE by the way – and get a build error:

Error occurred while packaging the application:

aapt tool failed:Warning: AndroidManifest.xml already defines versionCode (in http://schemas.android.com/apk/res/android); using existing value in manifest.

Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.

Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.

Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.

C:\Users\danfl\AppData\Local\Temp\7020cf25-1c31-4481-b943-8325017eeeab\AndroidManifest.xml:107: Tag <activity> missing required attribute name.

Here's my - app.xml code:

				<activity 
            		android:name="com.marpies.ane.twitter.LoginActivity"
            		android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen"
            		android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"/>

        			<activity> 
            			<intent-filter> 
                			<action android:name="android.intent.action.MAIN"/> 
                			<category android:name="android.intent.category.LAUNCHER"/> 
            			</intent-filter> 
            			<intent-filter> 
                			<action android:name="android.intent.action.VIEW"/> 
                			<category android:name="android.intent.category.BROWSABLE"/> 
                			<category android:name="android.intent.category.DEFAULT"/> 
                			<data android:host="twitter_access_tokens" android:scheme="com.runpee"/> 
			            </intent-filter> 
        			</activity> 
        		
				</application>

			</manifest>

BTW, I'm only using this ANE to send simple tweets ( AIRTwitter.updateStatus ). Are there any unnecessary tags here? 

Thanks,
Dan

**Comment by marpies** [comment]
It seems fine. I'm using the same XML in my test app and no problem there. Could you show your entire manifest element? Also what AIR version are you using?

**Comment by polyGeek** [comment]
Hey Marcel,

Thanks for the reply. Attached is my -app.xml

I'm using AIR 25

Dan

On Sat, Jul 22, 2017 at 5:48 PM, Marcel Piestansky <notifications@github.com

**Comment by marpies** [comment]
Hi Dan,

I don't see the attachment, could you try uploading it again?

Thanks.

**Comment by polyGeek** [comment]
Sorry about that.

On Sun, Jul 23, 2017 at 4:51 AM, Marcel Piestansky <notifications@github.com

**Comment by marpies** [comment]
I still don't see it. Maybe it cannot be attached via an email reply?

**Comment by iindieboy** [comment]
did you solve it? i have the same issue.

**Comment by polyGeek** [comment]
Sorry, no. I just switched to a different ANE. I'll come back and give this one a shot later. It's better than what I'm using from MilkmanGames.

**Comment by marpies** [comment]
I'm sorry but I haven't been able to reproduce this with the provided information. If you guys have a sample app descriptor XML that produces the error then please share it.

**Comment by polyGeek** [comment]
FYI, I got this issue fixed. Not sure how. I just started over from scratch.
