### ISSUE TITLE
Duplicate symbol in iOS native extension

### ISSUE THREAD

**Issue by sergueiglowbl** [marpies/AIRTwitter-ANE#2]
Hello, 
i'm trying to add two ANE(AIRTwitter-ANE and /AIRFacebook-ANE) in the same application.

Error occurred while packaging the application:
duplicate symbol _OBJC_CLASS_$_FREObjectUtils in: ... (full message 
[ErrorOccurredWhilePackagingTheApplication.txt](https://github.com/marpies/AIRTwitter-ANE/files/80929/ErrorOccurredWhilePackagingTheApplication.txt)

I found : https://forums.adobe.com/thread/2055508

Can you rename classe ? This is simle solution for now(or if you give other solution ? ).

Thanks. Serguei. Glowbl.

**Comment by marpies** [comment]
Thanks, I will look into it.

**Comment by marpies** [comment]
Just pushed a commit that should fix the issues. Use the updated ANE from the bin directory as well as updated AIRFacebook from your Gumroad library.

**Comment by sergueiglowbl** [comment]
Thank you for a very fast response.
Serguei.
