### ISSUE TITLE
User credentials are missing error

### ISSUE THREAD

**Issue by emreayaydin** [marpies/AIRTwitter-ANE#3]
Hello there!
Thank you for your extension! But, when I run the init function on IOS, i get "User credentials are missing" message. How can fix that, Where is my fault?

AIRTwitter.init( "3f9Pdz5VuAeJ5DFxUv68vHDIwsa", "IIjogkaSzBzKEmn7b2pAewEowvcHdDASD5452as8sDAy24aAm", "TwitterTestApp", onCredentialsChecked, true ) 

(These aren't my real key and secret)

Thank you!

**Comment by marpies** [comment]
Hi,

It isn't an error, it simply means the user hasn't logged in earlier in your app. The two booleans are provided to your callback to let you know if you need to authenticate your user or not. If `credentialsValid:Boolean` and `credentialsMissing:Boolean` are both `false` in your `onCredentialsChecked` callback then it means the user has logged in earlier at some point but the tokens can no longer be used with Twitter requests and you need to initiate login again.

**Comment by emreayaydin** [comment]
Thank you for reply :)

I have tried again like that. But this time I got a error "HTTP Status 401: unauthorized" :( Is there any example can I look?

if( AIRTwitter.init( "3f9Pdz5VuAeJ5DFxUv68vHDIwsa", "IIjogkaSzBzKEmn7b2pAewEowvcHdDASD5452as8sDAy24aAm", "TwitterTestApp", onCredentialsChecked, true ) ) {
                output.text =( "ANE initialized" );
            } else {
                output.text =( "ANE failed to init" );
            }

private function onCredentialsChecked( credentialsValid:Boolean, credentialsMissing:Boolean ):void {
            if( credentialsValid ) {
                output.text =( "User credentials are valid - no need to login again" );
                /\* You can use the rest of the AIRTwitter's API */
                return;
            } else if( credentialsMissing ) {
                output.text =( "User credentials are missing" );
                AIRTwitter.login( onTwitterLogin );
            } else {
                output.text =( "User credentials are invalid" );
            }

```
    }
```

**Comment by marpies** [comment]
Did you set **Callback URL** in your Twitter developer app?

**Comment by emreayaydin** [comment]
Yes I did. but, "Callback URL Locked"  was set as "yes". Now, I set  "Callback URL Locked" as "No". And than, It  worked AIRTwitter.login function. It opens the safari and return the application after the  Authorize web page. But the callback function doesn't triggered this time.

I'm sorry for my questions. But I need that.

protected function loginTw()
        {
            AIRTwitter.login( onTwitterLogin );
        }

```
    protected function onTwitterLogin( errorMessage:String, wasCancelled:Boolean ):void {
        output.text ="onTwitterLogin"
        if( errorMessage ) {
            output.text =( "Login error: " + errorMessage );
        } else if( wasCancelled ) {
            output.text =( "Login cancelled" );
        } else {
            output.text =( "Successfully logged in" );
        }
```

![twitterapp](https://cloud.githubusercontent.com/assets/4640113/12234823/5b605cac-b878-11e5-8116-42f7402d3f62.jpg)

**Comment by marpies** [comment]
I can't reproduce such issue so it's difficult for me to say what is wrong. 

If you're on a Mac, try opening Xcode and then from the menu go to Window > Devices (CMD + Shift + 2). Make a debug version of your IPA, then select your device in the Devices window, try to login again (you may want to set `forceLogin` to `true` in `AIRTwitter.login()`) and let me know what log messages with [AIRTwitter] tag you see.

**Comment by emreayaydin** [comment]
Okay, I'm using "loginWithAccount" function. And it's working perfectly. Thank you very much! You are great! :)
