### ISSUE TITLE
how to make the "Url Scheme" ?

### ISSUE THREAD

**Issue by badboybb** [marpies/AIRTwitter-ANE#4]
hello:
        I have a question in the ane, in the function of init , I don't know what is the URL SCHEME, Because my app don't have a url scheme, Can you help me??
@marpies 

        public function clickTwitterLoginIOSBtn():void {
		trace("clickTwitterLoginIOSBtn");
               if( AIRTwitter.init( CONSUMER_KEY, CONSUMER_SERCRET,URL_SCHEME,onCredentialsChecked, true ) ) {
		        AIRTwitter.login(onTwitterLogin);
}

**Comment by marpies** [comment]
Hi @badboybb,

The scheme can be some string that is (if possible) unique for your app. For example, you can choose your app id as your scheme.

Choosing the scheme should solve your other problem you [created here](https://github.com/marpies/AIRTwitter-ANE/issues/5).
