### ISSUE TITLE
why I can't get the PIN??

### ISSUE THREAD

**Issue by badboybb** [marpies/AIRTwitter-ANE#5]
after the authorization interface, I call back to my app directly. I don't see the web page with PIN. Can you tell me my progress is right???
     and when i login ,the log is "login cancelled","Returned to app manually after login attempt, thus login cancelled".
my code:

```as3
 public function clickTwitterLoginIOSBtn():void {
 if( AIRTwitter.init( CONSUMER_KEY, CONSUMER_SERCRET, URL_SCHEME, onCredentialsChecked, true ) ) {
	trace( "ANE initialized" );
} else {
	trace( "ANE failed to init" );
}
}
		
private function onCredentialsChecked( credentialsValid:Boolean, credentialsMissing:Boolean ):void {
	if( credentialsValid ) {
		trace( "User credentials are valid - no need to login again" );
		/* You can use the rest of the AIRTwitter's API */
		return;
	} else if( credentialsMissing ) {
		trace( "User credentials are missing" );
		AIRTwitter.login(onTwitterLogin, true);
	} else {
		trace( "User credentials are invalid" );
	}
       }
private function onTwitterLogin( errorMessage:String, wasCancelled:Boolean ):void {
      if( errorMessage ) {
		trace( "Login error: " + errorMessage );
	} else if( wasCancelled ) {
		trace( "Login cancelled:" + wasCancelled );
	} else {
		trace( "Successfully logged in" );
		const user:AIRTwitterUser = AIRTwitter.getLoggedInUser( onLoggedInUserRetrieved );
		if( user ) {
		// cached value returned
		}
	}
}
// if cached value is not returned callback will be triggered
private function onLoggedInUserRetrieved(user:AIRTwitterUser, errorMessage:String):void {
	trace( user.name );
}
```

**Comment by marpies** [comment]
You won't see the page with the PIN; the PIN is parsed automatically by the native libraries and you should be granted an access token.

**Comment by badboybb** [comment]
Now I can call back to my app ,but it always show the log of  "login cancelled  true"and"Returned to app manually after login attempt, thus login cancelled".
       I want to login my app through twitter, how can I success to login ????and how can I get the ID of  user who is login???Can you check my code ,where is the error caused the login cancelled????
     My log is:
 
      ANE initialized
      [AIRTwitter] User credentials result: missing
      User credentials are missing
      [AIRTwitter] onInvoke standard
      [AIRTwitter] onInvoke standard
      [AIRTwitter] Returned to app manually after login attempt, thus login cancelled
      Login cancelled:true
      [AIRTwitter] onInvoke standard
      [AIRTwitter] onInvoke openUrl

      my code is
public function clickTwitterLoginIOSBtn():void {
	trace("clickTwitterLoginIOSBtn");
       if( AIRTwitter.init( CONSUMER_KEY, CONSUMER_SERCRET, URL_SCHEME, onCredentialsChecked, true ) ) {
		trace( "ANE initialized" );
	} else {
		trace( "ANE failed to init" );
	}
}
	private function onCredentialsChecked( credentialsValid:Boolean, credentialsMissing:Boolean ):void {
	if( credentialsValid ) {
		trace( "User credentials are valid - no need to login again" );
		/* You can use the rest of the AIRTwitter's API */
		return;
	} else if( credentialsMissing ) {
		trace( "User credentials are missing" );
		AIRTwitter.login(onTwitterLogin);
	} else {
		trace( "User credentials are invalid" );
	}
}
private function onTwitterLogin( errorMessage:String, wasCancelled:Boolean ):void {
	if( errorMessage ) {
		trace( "Login error: " + errorMessage );
	} else if( wasCancelled ) {
		trace( "Login cancelled:" + wasCancelled );
	} else {
		trace( "Successfully logged in" );
		AIRTwitter.getLoggedInUser(onLoggedInUserRetrieved );
	}
}
// if cached value is not returned callback will be triggered
private function onLoggedInUserRetrieved(user:AIRTwitterUser, errorMessage:String):void {
	userID = user.id;
}

Please help me!!!!!
