### ISSUE TITLE
Why I always "login cancelled"???how can I success to get the user info who is login

### ISSUE THREAD

**Issue by badboybb** [marpies/AIRTwitter-ANE#6]
Now I can call back to my app ,but it always show the log of  "login cancelled  true"and"Returned to app manually after login attempt, thus login cancelled".

I want to login my app through twitter, how can I success to login ????and how can I get the ID of  user who is login???Can you check my code ,where is the error caused the login cancelled????
 My log is:

```
  ANE initialized
  [AIRTwitter] User credentials result: missing
  User credentials are missing
  [AIRTwitter] onInvoke standard
  [AIRTwitter] onInvoke standard
  [AIRTwitter] Returned to app manually after login attempt, thus login cancelled
  Login cancelled:true
  [AIRTwitter] onInvoke standard
  [AIRTwitter] onInvoke openUrl
```

  my code is

```as3
public function clickTwitterLoginIOSBtn():void {
trace("clickTwitterLoginIOSBtn");
if( AIRTwitter.init( CONSUMER_KEY, CONSUMER_SERCRET, URL_SCHEME, onCredentialsChecked, true ) ) {
trace( "ANE initialized" );
} else {
trace( "ANE failed to init" );
}
}
private function onCredentialsChecked( credentialsValid:Boolean, credentialsMissing:Boolean ):void {
if( credentialsValid ) {
trace( "User credentials are valid - no need to login again" );
/* You can use the rest of the AIRTwitter's API */
return;
} else if( credentialsMissing ) {
trace( "User credentials are missing" );
AIRTwitter.login(onTwitterLogin);
} else {
trace( "User credentials are invalid" );
}
}
private function onTwitterLogin( errorMessage:String, wasCancelled:Boolean ):void {
if( errorMessage ) {
trace( "Login error: " + errorMessage );
} else if( wasCancelled ) {
trace( "Login cancelled:" + wasCancelled );
} else {
trace( "Successfully logged in" );
AIRTwitter.getLoggedInUser(onLoggedInUserRetrieved );
}
}
// if cached value is not returned callback will be triggered
private function onLoggedInUserRetrieved(user:AIRTwitterUser, errorMessage:String):void {
userID = user.id;
}
```

Please help me!!!!!

**Comment by marpies** [comment]
Did you set correct URL scheme in your app descriptor and some callback URL in the Twitter app settings? See this screenshot:

![Twitter app settings](https://github.com/nst/STTwitter/raw/master/Art/twitter_app_settings.png)

Your app should be launched automatically after login in. If you are manually opening the app after login then that's why you see this message.

**Comment by badboybb** [comment]
![1](https://cloud.githubusercontent.com/assets/24217136/20779714/2a3fd952-b7b1-11e6-89b3-fbec187a7f8c.png)

![j6fq_ zdxgx ns97b7 6 u](https://cloud.githubusercontent.com/assets/24217136/20779691/0909b690-b7b1-11e6-892b-0baecf397a34.png)

I have set call back URL, and when I click the button of "login in twitter", then it open the Safari to Authorization, and I click "agree" , then it will be back to the login page of my app automatically. Why it will show that log of "Returned to app manually after login attempt, thus login cancelled".

**Comment by badboybb** [comment]
I also set the url scheme , but I don't know what is the correct URL scheme??

**Comment by badboybb** [comment]
How to set the correct URL scheme?? if my app name is "abc", my callback url is "https://twitter.com", how to make the url scheme??

**Comment by badboybb** [comment]
when I click the button of "login in twitter", then it open the Safari to Authorization, and I click "agree" , then it will find my app, and it will be back to the login page of my app automatically. Why it will show that log of "Returned to app manually after login attempt, thus login cancelled".

**Comment by marpies** [comment]
> How to set the correct URL scheme?? if my app name is "abc", my callback url is "https://twitter.com", how to make the url scheme??

The callback URL and URL scheme is not related. The URL scheme is just a string that identifies your app so that it can be launched from the browser.

What iOS version and device are you testing this on?

**Comment by badboybb** [comment]
I use ipad ,and my ipad version is 10.0.2

**Comment by badboybb** [comment]
when I click the button of "login in twitter", then it open the Safari to Authorization, and I click "agree" , then it will find my app, and it will be back to the login page of my app automatically. Why it will show that log of "Returned to app manually after login attempt, thus login cancelled".??????

**Comment by marpies** [comment]
It should not show that log if you are redirected to the app automatically. Maybe it's a bug, I'll check it out and try to fix it.

**Comment by badboybb** [comment]
OK!!! Can you see the Issue 4,?????there is my screenshot of my program and my log.

**Comment by marpies** [comment]
Yes, I see the screenshots. I'll try to fix this login bug and then you should be able to retrieve the user correctly.

**Comment by badboybb** [comment]
Please tell me a message if you check out.....Waitting for you

**Comment by marpies** [comment]
I'll check it out later today, can't work on it right now. I'll let you know when it's fixed.

**Comment by badboybb** [comment]
Are you find the the reason of the problem???

**Comment by marpies** [comment]
Try using the [latest release](https://github.com/marpies/AIRTwitter-ANE/releases).

**Comment by badboybb** [comment]
It still does not work, it is still loged "Login cancel true"and "[AIRTwitter] Login success".
![oewna7vl 87gtb0qc2rh 28](https://cloud.githubusercontent.com/assets/24217136/20871338/c32df222-bacf-11e6-87b6-794a23d49c84.png)

**Comment by badboybb** [comment]
When I click the button to login ,It will jump to Safari ,after I click the button of authorization, It will come back to my app. Is my progress wrong???

**Comment by badboybb** [comment]
It does work , Thank you very much!!!!
