### ISSUE TITLE
Issue in compiling ANE with other ANE's !

### ISSUE THREAD

**Issue by asim-karediya** [marpies/AIRTwitter-ANE#8]
Hi,

when i m including twitter ane in my adobe air app, it is showing me error when building .apk file. I have attached image of error if you can help out it will be great.

I m using other anes as well, like google analytics, google services, goviral, storekit, easypush, etc.

![twitter-error](https://cloud.githubusercontent.com/assets/17846009/20922541/488cd5f0-bbca-11e6-9210-a5b7956cece6.png)

**Comment by marpies** [comment]
Hi,

Did you try using the [latest version](https://github.com/marpies/AIRTwitter-ANE/releases)? In previous version, the AIRTwitter ANE included android-support-v4.jar so that may have caused conflicts with other ANEs if they include it as well. Try using the latest AIRTwitter ANE but do not include `com.marpies.ane.androidsupport.ane` in your project.

If that does not help, try packaging your app on the command line. The Flash Pro window does not show the entire error message so it's impossible to know what is wrong.

**Comment by asim-karediya** [comment]
Hi,

Just and update. Its working fine on IOS, but on Android its giving the same error even after using latest version and excluding this com.marpies.ane.androidsupport.ane.

Can you check at your end if its working on android with other anes ?

Thanks.

**Comment by asim-karediya** [comment]
Hi,

Ok i have found which ANE is conflicting with this, Its [Milkman's GoViral ANE](https://www.milkmanplugins.com/goviral-facebook-and-sharing-air-ane#) which is conflicting, when i exclude this, than project is packaging properly with twitter ANE.

This is a serious problem, can you please help me out in resolving this ? I need to include both GoViral and Twitter ANE in my project.

Thanks.

**Comment by marpies** [comment]
Hi,

Yes, it compiles fine with other ANEs that I'm using. I don't have GoViral ANE.

I'd like to help you but the error message you show doesn't tell me anything useful. I recommend you try to package the app on command line to get the full error message.

**Comment by asim-karediya** [comment]
Hi,

Alright i will try command line packaging as well and will post results. BTW can you point out any good tutorial on how to package using command line ?

Thanks.

**Comment by marpies** [comment]
I don't have any tutorial, but try reading through [the official documentation](http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac1e63e3d128cdca935b-8000.html).

**Comment by asim-karediya** [comment]
Hi,

Thanks for the reply.

Can you confirm that your AIRFacebook-ANE is working fine with this extension ?

**Comment by marpies** [comment]
Hi,

Yes, it works fine with AIRFacebook. You can try it yourself, the [ANE is available in the repository](https://github.com/marpies/AIRFacebook-ANE/blob/master/assets/com.marpies.ane.facebook.ane).

**Comment by asim-karediya** [comment]
Alright,

Finally the issue has been resolved. Milkman guy provided stripped version of Google Play Services that did the job and .apk is packaged successfully.

Thanks.
