### ISSUE TITLE
How to call the function of "public static function get accessToken():String{}"???

### ISSUE THREAD

**Issue by badboybb** [marpies/AIRTwitter-ANE#9]
I have a question , I want get the accessToken , But I don't know how to call the funtion of  "public static function get accessToken():String{}".Can you give me a example to get the access token????
![oj8 zfo_dk5x9 _q ietff](https://cloud.githubusercontent.com/assets/24217136/21035709/ececd20c-bdfb-11e6-88f3-a492f7332b62.png)

**Comment by marpies** [comment]
It's a getter so you don't type the parenthesis at the end, like this:

```as3
var token:String = AIRTwitter.accessToken;
trace( token );
```
